INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('1', 'SSP', 'Secretaria de Segurança Pública');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('2', 'IFP', 'Instituto Félix Pacheco');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('3', 'MA', 'Ministério da Aeronáutica');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('4', 'MM', 'Ministério da Marinha');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('5', 'MT', 'Ministério do Trabalho (para Carteira de Trabalho)');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('6', 'OAB', 'Ordem dos Advogados do Brasil');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('7', 'CREA', 'Conselho Regional de Engenharia e Arquitetura');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('8', 'CRM', 'Conselho Regional de Medicina');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('9', 'ME', 'Ministério do Exército');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('10', 'CBM', 'Corpo de Bombeiros Militar');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('11', 'CRO', 'Conselho Regional de Odontologia');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('12', 'CRF', 'Conselho Regional de Farmácia');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('13', 'RNE', 'Registro Nacional de Estrangeiro (RNE)');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('14', 'DPGE', 'Defensoria Pública Geral do Estado');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('15', 'DI', 'Departamento de Investigações');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('16', 'DPTC', 'Departamento de Polícia Técnico Científica');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('17', 'DESP', 'Departamento Estadual de Segurança Pública');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('18', 'DFSP', 'Departamento Federal de Segurança Pública');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('19', 'DIEM', 'Diretoria de Identificação Enéas Martins');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('20', 'DGPC', 'Diretoria Geral da Polícia Civil');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('21', 'DSG', 'Divisão de Segurança e Guarda');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('22', 'EAPJU', 'Estado do Amazonas Poder Judiciário');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('23', 'GISI', 'Gabinete de Investigações Serviço de Identificação');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('24', 'GEJ', 'Gerência Estado de Justiça');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('25', 'IC', 'Instituto de Criminologia');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('26', 'ID', 'Instituto de Identificação');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('27', 'IICM', 'Instituto de Identificação Carlos Menezes');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('28', 'IIEP', 'Instituto de Identificação do Estado do Paraná');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('29', 'IIDAMP', 'Instituto de Identificação Dr. Aroldo Mendes de Paiva');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('30', 'IIDML', 'Instituto de Identificação Médico Legal');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('31', 'IIRGD', 'Instituto de Identificação Ricardo Gublenton Daunt');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('32', 'IITP', 'Instituto de Identificação Técnica Policial');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('33', 'IMLC', 'Instituto de Medicina Legal e Criminalística');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('34', 'IPT', 'Instituto de Polícia Técnica');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('35', 'IFP', 'Instituto Felix Pacheco/Instituto de Identificação Felix Pacheco');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('36', 'IGP', 'Instituto Geral de Perícia');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('37', 'INI', 'Instituto Nacional de Identificação');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('38', 'IPF', 'Instituto Pereira Faustino');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('39', 'ITB', 'Instituto Tavares Buril/Instituto de Identificação Tavares Buril');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('40', 'JUIJ', 'Juizado da Infância e da Juventude');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('41', 'MJ', 'Ministério da Justiça');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('42', 'PJEG', 'Poder Judiciário do Estado de Goiás');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('43', 'PCIID', 'Polícia Civil Instituto de Identificação');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('44', 'PDFII', 'Polícia do Distrito Federal Instituto de Identificação');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('45', 'PTC', 'Polícia Técnico Científica');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('46', 'RBR', 'República do Brasil');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('47', 'RFBR', 'República Federativa do Brasil');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('48', 'SCJDS', 'Secretaria Coordenadora de Justiça e Defesa Social');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('49', 'SJTC', 'Secretaria da Justiça do Trabalho e Cidadania');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('50', 'SJS', 'Secretaria da Justiça e da Segurança');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('51', 'SPSP', 'Secretaria da Polícia e Segurança Pública');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('52', 'SSDS', 'Secretaria da Segurança e da Defesa Social');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('53', 'SSPDC', 'Secretaria da Segurança Pública e Defesa da Cidadania');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('54', 'SSPDS', 'Secretaria da Segurança Pública e Defesa Social');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('55', 'SECC', 'Secretaria de Estado da Casa Civil');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('56', 'SEDS', 'Secretaria de Estado da Defesa Social');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('57', 'SEJSP', 'Secretaria de Estado da Justiça e Segurança Pública');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('58', 'SEPC', 'Secretaria de Estado da Polícia Civil');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('59', 'SES', 'Secretaria de Estado da Segurança');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('60', 'SESPDC', 'Secretaria de Estado da Segurança Pública e Defesa do Cidadão');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('61', 'DESIPE', 'Secretaria de Estado de Justiça e Interior');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('62', 'SESDC', 'Secretaria de Estado de Segurança Defesa e Cidadania');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('63', 'SESP', 'Secretaria de Estado de Segurança Pública');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('64', 'SESPDS', 'Secretaria de Estado de Segurança Pública e Defesa Social');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('65', 'SJDS', 'Secretaria de Justiça e Defesa Social');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('66', 'SJSP', 'Secretaria de Justiça e Segurança Pública');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('67', 'SJIS', 'Secretaria de Justiça, Interior e Segurança');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('68', 'SSI', 'Secretaria de Segurança e Informações');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('69', 'SPCII', 'Segurança Pública e Cidadania Instituto de Identificação');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('70', 'SI', 'Serviço de Identificação');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('71', 'SIC', 'Serviço de Identificação e Criminalística');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('72', 'SPC', 'Superintendência de Polícia Civil');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('73', 'SPTC', 'Superintendência de Polícia Técnico- Científica');
INSERT INTO orgao_expedidor (id, sigla, nome) VALUES ('74', 'SGPJ', 'Superintendência Geral de Polícia Judiciária');


